/// Flutter icons SocialIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SocialIcons
///      fonts:
///       - asset: fonts/SocialIcons.ttf
///
/// 
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class SocialIcons {
  SocialIcons._();

  static const icons = 'SocialIcons';

  static const IconData twitter = const IconData(0xf099, fontFamily: icons);
  static const IconData github_circled = const IconData(0xf09b, fontFamily: icons);
  static const IconData youtube_play = const IconData(0xf16a, fontFamily: icons);
  static const IconData instagram = const IconData(0xf16d, fontFamily: icons);
  static const IconData whatsapp = const IconData(0xf232, fontFamily: icons);
  static const IconData facebook_squared = const IconData(0xf308, fontFamily: icons);
  static const IconData linkedin_squared = const IconData(0xf30c, fontFamily: icons);
}
